
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    #servlet:
    #context-path: /car-rental/api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realestate_db
    username: realestate_user
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


cosmosRestate:
  app:
    jwtSecret: cosmosREstate@12
    jwtExpirationMs: 86400000


logging:
  file:
    name: logs/cosmosrealestate.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.realestate]': DEBUG

